name: CI
run-name: 'CI for PR #${{ github.event.pull_request.number }}'
on:
  pull_request:
    branches:
      - main
jobs:
  CI-steps:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job from ${{ github.actor }} was automatically triggered by a ${{ github.event_name }} event, running on a ${{ runner.os }}"
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run npm install
        run: npm i
      - name: Run tests with coverage
        run: npm run test:coverage
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage
      - name: Run eslint
        run: npm run lint
      - name: Run prettier
        run: npx prettier . --check
      - name: Run build
        run: npm run build
      - run: echo "💼 This job's status is ${{ job.status }}."
